name: Build Quartz Site
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: konstfish/quartz-build-action@main
        with:
          source: ./
          quartz_config: .github/quartz/quartz.config.ts
          quartz_layout: .github/quartz/quartz.layout.ts
          quartz_icon: .github/quartz/icon.png
          quartz_banner: .github/quartz/og-image.png

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public # or your Quartz output directory
          publish_branch: gh-pages
          force_orphan: true #if you need to create the gh-pages branch.