name: Check Markdown for broken links

on:
  push:
  schedule:
    - cron: '0 0 * * 0' # @weekly

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
